### ISSUE TITLE
Refactoring: Make request retrieval leaner

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#100]
Make the way requests are loaded in FilteredList.jsx leaner.

**Comment by timjb** [comment]
@Maurice22 I'd like to work on this. Here's what I would do:

Break the `FilteredList` component into three components:

* A component `RequestsForHelpFilteredByLocation` which is responsible for loading and displaying all requests for help in the case that the user has entered a postal code,
* A component `RequestsForHelpSortedChronologically` which is responsible for loading and displaying all requests for help sorted by timestamp, providing a button to load more at the end.
* A component `FilterableRequestsForHelp` which includes the search field and uses `RequestsForHelpSortedChronologically` or `RequestsForHelpFilteredByLocation` depending on whether the search input is empty or not.

What do you think?

**Comment by Maurice22** [comment]
@timjb I was working on this as part of #56 and think it is fine for now, no need to break it down into separate components at this time. Thanks anyways.
