### ISSUE TITLE
Pass Zip Code from Overview to NotifyMe

### ISSUE THREAD

**Issue by funtonia** [kenodressel/quarantine-hero#111]
When entering one's zip code in Overview (when searching for help requests) & then clicking the "Benachrichtige mich wenn jemand Hilfe braucht!"-Button, the zip code is lost and has to be reentered on NotifyMe. Would be nice to keep that zip code to prevent spelling mistakes & simply increase UX.

**Comment by Maurice22** [comment]
This is a good idea in general, but I think it conflicts with our plans regarding the google maps api reintegration. Here, we will allow free text search in the overview and on the entry page but want to limit the input to only plz in /notify-me and /ask-for-help.

@tgraupne @florianschmidt1994 Opinions?

**Comment by Maurice22** [comment]
Thank you very much @funtonia, we discussed this internally and came to the conclusion that passing the Zip code from the general search to /notify-me would collide with the aim to keep the platform backwards compatible.

What do we mean by that:
On the overview page, a user can search for a broad range of locations (i.e. "Berlin"). The resulting zip code from the Google API will not represent the persons location precisely. If we would take this location over to /notify-me, we would store this (unprecise) location. However, if at some point we decide against using google maps, we would not be able to assure a good matching anymore. Hence, we ask the users for their specific ZIP code in the /notify-me.

Hence, we will close this issue for now.
