### ISSUE TITLE
Design interface for data exchange with other platforms

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#116]

**Comment by tgraupne** [comment]
We are currently waiting on the first proposals for other organisations.

**Comment by tgraupne** [comment]
WE started the collaboration with some meetings and created the Github organisation: CoronaSupportNetwork. Discussion regarding the data model for our cross-platform broker are now here: https://github.com/CoronaSupportNetwork/CoronaHelpBroker/issues/1
