### ISSUE TITLE
Feature: make address on post clickable and use as filter

### ISSUE THREAD

**Issue by jagaSto** [kenodressel/quarantine-hero#127]
Idea: Make the address on a post on the overview page clickable and use it to filter the existing entries. Could be a cool feature to quickly filter for entries in a specific location, without having to navigate back to the main filter

![Screenshot 2020-03-23 at 14 58 20](https://user-images.githubusercontent.com/20641332/77324412-fd9f3900-6d16-11ea-8ff7-9a304a0e9a55.png)

e.g. when clicking on  **30167 Hannover, Deutschland**, it would show me all posts for that location (probably resetting the entered radius then)

**Comment by marko-ignjatovic** [comment]
May I try this one?

**Comment by marko-ignjatovic** [comment]
After we filter entires (locally) on address click, how we gonna reset filter? Should we add some button?

**Comment by florianschmidt1994** [comment]
Yeah go ahead! 💪 

I think something like a small `X` inside search bar might be nice. Have you checked how we would currently delete a filter when typing it in? I believe it is just by typing _backspace_, right?

Try assigning the issue to yourself, ping me if it doesn't work and I'll do it for you :)

**Comment by marko-ignjatovic** [comment]
@florianschmidt1994 I forgot to tell you, but it seems like I can't assign myself.

**Comment by florianschmidt1994** [comment]
Done ✔️
