### ISSUE TITLE
Disable onClick redirect for entries of a user

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#129]
As a user won't give help to a request created by the user himself, we can prevent the redirect to the /offer-help page in this case.

**Comment by marko-ignjatovic** [comment]
May I take this one ?

**Comment by Maurice22** [comment]
@marko-ignjatovic Thanks for the interest, but we've already got a PR regarding this issue (and now also linked 😃 ) and are currently deciding on what the best user experience actually is. But thank you anyways a lot for your interest, maybe there's another Issue that catches your eye 😃

**Comment by Maurice22** [comment]
Closed via #134
