### ISSUE TITLE
Navigation broken

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#149]
- Security page not visible when not logged in

**When logged in**
- Hilfe anfragen leads to dashboard
- Security leads to dashboard
- possibly more

@florianschmidt1994 @tgraupne @kenodressel @jagaSto 
**This is a blocker for a new release**

**Comment by Maurice22** [comment]
Probably related to PR #139

**Comment by koiranos** [comment]
@Maurice22, @florianschmidt1994, I understand what I did wrong and I am fixing it. One question though Meine Übersicht link were should lead to?

**Comment by kenodressel** [comment]
Its already fixed in develop, pushed a fix :)

**Comment by tgraupne** [comment]
This seems fixed to me as well.
Can we close this @Maurice22 @kenodressel
