### ISSUE TITLE
Finding Postal codes only finds exact matches

### ISSUE THREAD

**Issue by heikotroetsch** [kenodressel/quarantine-hero#15]
When searching for postal codes only exact matches are shown. 

It would be great to display the closest locations to your postal code.

**Comment by heikotroetsch** [comment]
Just checked out the code, it seems its just not activated. 

Btw: The Application design with firebase as a backend and pretty much only frontend ist really nice!

**Comment by kenodressel** [comment]
Not sure how you mean "not activated". We have a filtering implemented that allows you to type the first numbers of your zip code and by this see nearby results.

**Comment by heikotroetsch** [comment]
In your code here const isMapsApiEnabled = false;

On your live website it seems also set to false since when looking for zip code the closest isn't shown and the suggestions aren't there. 

I might be wrong but as I see it this feature is set disabled.

**Comment by kenodressel** [comment]
Correct. This is because the Google Maps API is too expensive for the traffic we have. So we are waiting for a sponsoring from Google and if we get it, we re-enable the Google Maps integration.
