### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#156]
Build a page similar to /success, that indicates that the performed operation failed.

**Comment by Maurice22** [comment]
![Bildschirmfoto 2020-03-26 um 11 26 15](https://user-images.githubusercontent.com/20804369/77636628-b1d9d300-6f54-11ea-93f3-42de4000cc9d.png)

**Comment by Maurice22** [comment]
Bonus points if the icon can be randomly selected from a list of svgs (notify @Maurice22 ) for the files.

**Comment by marko-ignjatovic** [comment]
May I try to do this one?

**Comment by Maurice22** [comment]
Sure @marko-ignjatovic , find the svgs here: https://we.tl/t-mpy6nADMo0

**Comment by jagaSto** [comment]
fixed with #163
