### ISSUE TITLE
Discuss usage of error reporting tool

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#158]
With more traffic and users, we have an increase of reports where stuff is not working properly. We should discuss the usage of an error monitoring tool such as Sentry. Maybe Firebase has something like this integrated as well?

- [ ] Investigate error reporting tools
- [ ] Discuss GDPR implications
- [ ] Discuss if the cost / benefit is worth adding something like this in the first place

Feedback appreciated! @kenodressel @tgraupne

**Comment by Maurice22** [comment]
I checked out Sentry and it was really able to set up. It only gets activate if the user accepted cookies in my current version. I'm also in contact with them about getting a free plan as we are open source.

**Comment by florianschmidt1994** [comment]
Nice! Should we go with the free version for now / trail for 14 days as we wait for feedback? What do you think?

**Comment by Maurice22** [comment]
Sure, it's really only 4 lines of code or so in my local branch wo I will activate the trial and create a PR for this
