### ISSUE TITLE
Locations are localized to input

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#160]
Currently, autocomplete suggestions are localized and are getting used as input for the database. Hence, we could run into issues where the location is not displayed in german (see attachment)
![image](https://user-images.githubusercontent.com/20804369/77646491-ee152f80-6f64-11ea-9664-31ecadb73cc0.png)

**Comment by florianschmidt1994** [comment]
Closed with https://github.com/kenodressel/quarantine-hero/pull/162
