### ISSUE TITLE
Update release process and document it properly

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#161]
We've recently discussed to switch our release process 
- from having a PR from develop to master
- to merging all PRs directly into master again

Why?
We've noticed that with our model of creating releases from develop we've introduced quite some overhead for the maintainers by periodically having to sit down (currently daily) and creating a release PR. 
Originally we were hoping that this would give us the opportunity to thoroughly review everything before creating a release, but in practice we've introduced a range of bugs with this model anyway, essentially leaving us with little benefit and more overhead.

We've therefore decided to switch to a model where we have PRs against master again and increasing the thoroughness with which we review those PRs (e.g. by adding testing).

We should document this decision, its' consequences and the motivation in order to communicate it well to all collaborators, especially with changing this model again so quickly after the course of a week.

- [ ] Document the "how"
- [ ] Document the "why"
- [ ] Discuss squash & merge vs rebase & merge
- [ ] Discuss the formalities of linting, testing and review

Here is a little overview of what I'm proposing we should do:

1. All features except hot fixes will be done as PRs against master
2. Maintainers of the project review those PRs
3. PRs will be rebased & merged OR squashed & merged
4. A framework for testing will be added
5. Tests will be written for existing features
6. New features will only be merged when covered by tests (there is a little leeway here, the reviewer can decide / discuss this) 
5. Continuous testing & linting will be done against the PR
6. After merging a PR into master we will run tests. If tests are successfull we deploy to GH pages, if tests fail we don't and notify the maintainers that master is broken

Regarding 3.: I'm strongly in favor of squash & merge, because it will
- Allow us to atomically roll back PRs by reverting a commit if something should change
- Allows the reviewer to help with a clear and concise commit message
- Gives us a nice & clean history (ok, this is a little pet peeve of mine but I still think it's nice)

Please leave your feedback underneath this issue @tgraupne @kenodressel @jagaSto @Maurice22

**Comment by Maurice22** [comment]
So hotfixes will then be normal pushes to master? I would suggest also creating a PR for those to have at least a second pair of eyes on them in order to not have a hotbreak :P

**Comment by florianschmidt1994** [comment]
I would say it's up to the discretion of the maintainer, but I would be open to always have those as PRs as well. I think it would depend on the severity and urgency of the hotfix, I'm not sure if there's a good rule of thumb here

**Comment by jagaSto** [comment]
I like the suggestions! 


> 1. All features except hot fixes will be done as PRs against master

I would vote for implementing PRs here as well, so other reviews can quickly check out the branch and confirm that the changes indeed fix the problem

> Regarding 3.: I'm strongly in favor of squash & merge, because it will

👍 

> 6. New features will only be merged when covered by tests (there is a little leeway here, the reviewer can decide/discuss this)

Should we discuss the PR review process in more detail? E.g. the number of required reviews, etc.? At this point we could also introduce more labels, e.g. `ready for review`, `changes requested` to get more transparency on the current status for a PR

**Comment by florianschmidt1994** [comment]
Regarding your last point, yes maybe it would make sense to discuss this a little more! Me personally I would prefer a model where a PR should only be opened when it is ready to merge (from the contributers perspective) and don't have WIP pull requests. Changes reflected could then be annotated via the GitHub Feature and we would not have to add additional labels
