### ISSUE TITLE
Setup quarantänehelden.org domain

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#170]
I'm getting multiple reports from people who use the domain with umlauts and are seeing the parking domain. As we already own the domain quarantänehelden.org we should check what keeps us from setting it up and do it eventually

**Comment by kenodressel** [comment]
The following domains now redirect to quarantaenehelden.org:
quarantänehelden.de
quarantänehelden.org
quarantaenehelden.de

**Comment by florianschmidt1994** [comment]
Yeeah 💯 Thanks!
