### ISSUE TITLE
Add supporters to our FAQ

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#172]
We have been supported by different people and organizations, and some of them are asking if we could possibly link to them on our website. 

On idea that we came up with is to add a "Wer unterstützt uns" question to the FAQ section, where we could mention them and add a backlink to their website.

Opinions?

**Comment by kenodressel** [comment]
I think its a good, non intrusive way to show the supporters.

**Comment by Maurice22** [comment]
I also like the idea

**Comment by tgraupne** [comment]
Imho, this would better fit to the press page. Because this page's purpose isn't just to list press listings of us but also work as an entry point for press representatives. Hence, mentioning our supporters here would fit this purpose. What are you thinking?

**Comment by tgraupne** [comment]
Any other thoughts?

**Comment by kenodressel** [comment]
Some days ago we discussed a separate supporter page. The question is, can we fill it with content and where would we add the link to this page?
