### ISSUE TITLE
Error in Auth dependency

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#173]
We currently have `react-with-firebase-auth` and `react-firebase-hooks` and use mostly the latter package. Additionally we have possible errors linked to `react-with-firebase-auth`:

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in withFirebaseAuth(Signin) (at App.jsx:106)
console.<computed> @ 0.chunk.js:149557
```

**Comment by florianschmidt1994** [comment]
I want to wait for https://github.com/kenodressel/quarantine-hero/pull/168 to be merged, because it touches the same parts
