### ISSUE TITLE
Add Pagination to frontpage

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#18]
Cloud Firestore has several features to help you manage queries that return a large number of results:

- Cursors, which allow you to resume a long-running query.
- Page tokens, which help you paginate the query results.
- Limits, which specify how many results to retrieve.
- Offsets, which allow you to skip a fixed number of documents. (DO NOT USE, 1 read per skipped doc)

**Comment by Maurice22** [comment]
I am working on this over at User/Repository@SHA: Maurice22/quarantine-hero@8c87da33746d67563e31d7301e4606f0f6bb3d1e

**Comment by Maurice22** [comment]
So there is an issue: If we use pagination, client-side filtering of locations does not work anymore (as we won't search the whole database). I wanted to fix this by filtering the location on the database as well but it turns out that more or less firebase only allows for one filter.

Because of that I would suggest to disable pagination if a user searches for a location. What do you think? Do you have other ideas?

**Comment by kenodressel** [comment]
@Maurice22 Yes thats a problem but it also means we significantly reduce reads.
Our plan for today is to re-enable the google maps integration and therefore also re-enable a proper search. So I think its fine if you build it and we merge it after we re-enable the maps api.

**Comment by Maurice22** [comment]
@kenodressel Please check out my version at Maurice22/quarantine-hero@383f2c7246739be42cff0dc542c75cfca004a6ba . I completely redesigned the way queries are done, including support when maps API is enabled. Can you give it a test? If everything works fine, I will create a PR for it.

**Comment by Maurice22** [comment]
Ah yeah and of course I added pagination there :D Check the commit messages for more info.

**Comment by kenodressel** [comment]
I took a look and it seems fine to me. Are you available for a call (send mail to help@quarantaenehelden.org) so we can include you better in our planning?

**Comment by Maurice22** [comment]
Closed in #46
