### ISSUE TITLE
Provide a config parameter for i18next debug logging

### ISSUE THREAD

**Issue by tgraupne** [kenodressel/quarantine-hero#181]
Just recently, we deactivated debug logging for i18next.
However, it might be a good idea to have those logs in testing scenarios.
Therefore, it would be great to introduce a parameter for this.

**Comment by jakob-ed** [comment]
Would it be enough to just enable debug logging if `REACT_APP_ENV` is something other than production or would you want to add a `.env.test` file with a new variable specifically for i18next debug logging? First two options that come to my mind. :)

**Comment by kenodressel** [comment]
@jakob-ed You are on the right track. Right now we have `.env` and `.env.development` and our target is to have an explicit env variable to enable debug logging. The debug logs from i18n package is only the beginning but for now its the scope of this ticket. Later we would like to have a global debug logging enabled with this env variable.

**Comment by jakob-ed** [comment]
Then I would for now introduce a flag `REACT_APP_DEBUG_LOGGING` in the `.env.development` that can be set to switch it on or off. What do you think?

**Comment by kenodressel** [comment]
yes sounds good. I will assign you the issue :)

**Comment by kenodressel** [comment]
We should also make sure that the flag is false in the prod config

**Comment by jakob-ed** [comment]
@kenodressel opened a PR now and would be happy about a review. Somehow I can't request a review right from the PR, probably because I'm not a collaborator.
