### ISSUE TITLE
Configure Cypress tests to be mobile-first

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#184]

**Comment by florianschmidt1994** [comment]
We should think about how to refactor the tests for mobile / desktop. I'm not a 100% sure if just changing the viewport will suffice, b.c. some tests rely on the navigation elements, which are different on different viewports.

**Comment by tgraupne** [comment]
> We should think about how to refactor the tests for mobile / desktop. I'm not a 100% sure if just changing the viewport will suffice, b.c. some tests rely on the navigation elements, which are different on different viewports.

That is correct, afaik, there are 1 or 2 tests which fail because of missing navigation elements. And yes, we should refactor them and I wanted to do this within this PR. But I'll probably need some help with that 🙈
