### ISSUE TITLE
Github Actions Fails if there is no change to the deployed code

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#194]
Right now if we push something to master that does not result in a change of the deployed code (eg. readme or firebase functions) it "fails". We should discuss if this is an intended behavior or a bug. I would classify it as a bug because the overall summary is "failed" for these runs which lets me assume that there might be something wrong with the build / pipeline but its expected.

**Comment by florianschmidt1994** [comment]
I agree that failed is the wrong report. We should see that if there is no change we either
a.) don't deploy
or
b.) the deploy will not fail

**Comment by kenodressel** [comment]
i would prefer a) but i am not sure if its possible. so I would say the easy solution for now is b). Could be done with `git commit --allow-empty`
