### ISSUE TITLE
Set requests to "fullfilled" instead of "deleted" 

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#21]
that shows when a person has been "helped"? Also then instead of deleting the message, people visiting could see how many people have been helped -- which makes it clear that the platform is "successful". Let me know what you think!

**Comment by tgraupne** [comment]
https://github.com/kenodressel/quarantine-hero/issues/107#issue-585591381

**Comment by tgraupne** [comment]
There are further interesting ideas in #107 by @jagaSto and @timjb 
https://github.com/kenodressel/quarantine-hero/issues/107#issue-585591381

https://github.com/kenodressel/quarantine-hero/issues/107#issuecomment-602118875

**Comment by jagaSto** [comment]
**backlog**
* main page timeline (too sophisticated for now)

**planned for now**

* option for help seekers to set the post to solved and to delete them
* tabs for open/solved posts on a user dashboard
* confirmation dialog with a hint that the post can also be set to solved instead
* optional: firebase job that reminds creators of old entries to set a job to solved, if applicable
* optional: hint in email for creator that he can set issues to solved

**Comment by Maurice22** [comment]
Closed in #153
