### ISSUE TITLE
Map/List switch is not visually centered

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#214]
As you can see in the image below, the centerline of the toggle button is not visually centered on the page. Instead, the whole button group is centered on the page.

Caused in #171.

<img width="645" alt="Bildschirmfoto 2020-04-07 um 00 45 50" src="https://user-images.githubusercontent.com/20804369/78612249-26701400-7869-11ea-89ed-3716632e6ec8.png">

**Comment by tgraupne** [comment]
Not relevant anymore.
