### ISSUE TITLE
Typo in quarantaenehelden_b_russian.pdf

### ISSUE THREAD

**Issue by moebelwagen** [kenodressel/quarantine-hero#223]
There is a typo in the main text in the Russian information poster. The whole text should be:
> Мы создали quarantaenehelden.org для того, чтобы люди могли поддержать тех, кому может понадобиться дополнительная помощь во время карантина. Эта платформа объединяет тех, кто нуждается в помощи или не может выходить из дома, с местными добровольцами, которые готовы выполнить поручения, доставить продукты, выгулять домашних животных, а также оказать другую помощь. Вы можете зарегистрироваться на нашем веб-сайте, чтобы попросить о помощи или помочь другим. Давайте поддержим друг друга!

**Comment by tgraupne** [comment]
Hi @moebelwagen, thank you very much for your feedback. We forwarded this to the person in charge of those translations. We are confident, that we can fix this error soon.
