### ISSUE TITLE
Remove logo duplication on frontpage

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#235]

**Comment by jakob-ed** [comment]
Do you mean the duplication on mobile?
![image](https://user-images.githubusercontent.com/15202881/79767830-33413d00-832a-11ea-9b0b-a74ad0f952f6.png)

If so, I would propose to remove the lower one to keep the top one consistent on all the subpages. It would then look like this on the front page: 
![image](https://user-images.githubusercontent.com/15202881/79768013-77344200-832a-11ea-9091-11fa750e2ab3.png)

**Comment by kenodressel** [comment]
yes looks good!
