### ISSUE TITLE
Enable internationalization

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#24]
Make app available in multiple languages, depending on the location of the user.

To be clarified: Should only the text be changed or should geofilters be applied.

Possible solution: One work stream for internationalization (text) and one for the data-related part.

**Comment by kenodressel** [comment]
Would be awesome! I think we could manage the data / backend part but need help with the frontend!

**Comment by yorickreum** [comment]
We can help with the frontend. Let's use react-i18next? https://github.com/i18next/react-i18next
To clarify: You want to keep one domain (quarantaenehelden.org is in German…) and one Firebase backend?

**Comment by kenodressel** [comment]
Yes sounds good. I would try to not use text as keys but rather use defined variables. Other than this I think you can start :)

**Comment by wiredancer** [comment]
With the .org domain, no hint is currently given to the user whether this site applies to other German-speaking countries as well. At the very least, it would be good to add a country selection input where you specify the zip code. It is not clear what country's zip codes are expected there.

P.S. My parents live in Switzerland and I am therefore looking for a solution which works in Switzerland

**Comment by Maurice22** [comment]
We are working on a new way to specify the locations and will take this into account, thanks!

**Comment by kenodressel** [comment]
> With the .org domain, no hint is currently given to the user whether this site applies to other German-speaking countries as well. At the very least, it would be good to add a country selection input where you specify the zip code. It is not clear what country's zip codes are expected there.
> 
> P.S. My parents live in Switzerland and I am therefore looking for a solution which works in Switzerland

We are working on re-integrating a proper location based search which also includes countries (eg. Switzerland, Austria and Südtirol)

**Comment by yorickreum** [comment]
I started to work on this on https://github.com/yorickreum/quarantine-hero/tree/internationalization – by now, I added react-i18next and moved all strings from components to central de/translation.json.

**Comment by yorickreum** [comment]
One question to discuss: For views with a lot of text, like the legal details or the privacy policy I would not like to do translations via i18n since this led to huge amounts of text in the translation.json files.
How should we do this? Maybe by transferring the content into Markdown files?

**Comment by tgraupne** [comment]
@yorickreum, that is a great question. I'll do some research and get back to you.
For now, I just want to thank you already for your contributions.

@wiredancer, your point about some hints regarding other German-speaking countries is interesting. Even though we released full compatibility to 4-digit zip codes, I couldn't find text hinting to Switzerland or Austria. I'll follow up on that too.

**Comment by tgraupne** [comment]
I followed up internally and we'll put your remarks on our internal todo list.
Thanks again for your input. 🍾
