### ISSUE TITLE
Improve email-verification redirect logic

### ISSUE THREAD

**Issue by jagaSto** [kenodressel/quarantine-hero#241]
Currently, when attempting to verify your email address, you need to click the verification link in the email, which takes you to the google auth success page. It would be better UX however if the link would redirect you to the website again after successful verification, similar to the sign-in logic for the `notify-me` component.
Also, if you verify your email address and do *not* reload the page, you need to re-login for the website to notice that your email is indeed verified. This is also bad UX and could be resolved as well by improving the redirect logic to automatically redirect the user, and reload the page automatically.

**Comment by Maurice22** [comment]
Please see my comment on the PR for potentially improving the UX a lot more by implementing the email verification, password reset, etc. directly on the QH website instead of the generic google one.
