### ISSUE TITLE
Sendgrid redirect triggers thunderbird warning

### ISSUE THREAD

**Issue by DaAngus** [kenodressel/quarantine-hero#25]
(english thunderbird)

> The link you just clicked seems to lead to another site than what the link text indicated. This is sometimes used for tracking whether you clicked the link, but it could also be a scam.
>
>The link text indicated that the link would lead to www.quarantaenehelden.org, but it leads to (id).ct.sendgrid.net.

It could scare people away from clicking.

**Comment by kenodressel** [comment]
Hello @DaAngus,
good find. Right now this due to SendGrids tracking. We will consider removing it. I will update this issue accordingly.
Best,
Keno

**Comment by kenodressel** [comment]
Tracking removed. Links should be fine now.
