### ISSUE TITLE
implement logo of BMG on landing page

### ISSUE THREAD

**Issue by milenasoga** [kenodressel/quarantine-hero#259]
<img width="283" alt="03" src="https://user-images.githubusercontent.com/64332518/80376475-25e00180-889a-11ea-8bb2-71b921b7785c.png">

logo source: https://www.zusammengegencorona.de/zgc.svg

**Comment by Maurice22** [comment]
@milenasoga Is there also a complete logo including the text on the left?

**Comment by milenasoga** [comment]
@Maurice22 no, not yet, would it be helpful?

**Comment by Maurice22** [comment]
I just found out, that the text on the left does not belong to the CI of BMG, hence we should be fine with the reference you provided. Thanks for the quick response.
