### ISSUE TITLE
Typo on main

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#26]
"Lokal" Section Haus Mitbewohner\*innen > Haus-mitbewohner\*innen

**Comment by Maurice22** [comment]
Other "Satzbau" issue: 

On /ask-for-help "Bitte hier stellt keine ANGEBOTE rein" -> should be "Bitte stellt hier keine ANGEBOTE ein"

@kenodressel  Could someone of the core team fix that?

**Comment by kenodressel** [comment]
Both typos fixed in presse-update branch
