### ISSUE TITLE
Add deep-link to entry in email

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#261]
~As part of our phone hotline we should add a link back to the entry to the emails. Not only will this allow hotline members to easily detect answers to entries, but it will also be helpful to show users that they can mark their entry as solved~

EDIT to make the scenario a little more clear:

A person (helpee) posts an entry (entry) to our website asking for help. Another person (helper) offers to help them. (offer-help)
We already send an email to the helpee that somebody is offering help. This email does currently not include a link to the entry. With the PR solving this issue we will be able to add such a link to the email

Related to #245, possible duplicate of #245

**Comment by Maurice22** [comment]
@florianschmidt1994 Can you clarify on this? Which email do you mean? AFAIK, the notification emails for people offering help already include the link to the entry.

**Comment by florianschmidt1994** [comment]
Yes I'll try.

A person (_helpee_) posts an entry (_entry_) to our website asking for help. Another person (_helper_) offers to help them. (_offer-help_)
We already send an email to the _helpee_ that somebody is offering help. This email does currently not include a link to the _entry_. With the PR solving this issue we will be able to add such a link to the email
