### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#29]
Hi, I'm not too familiar with React and Firebase. Do those technologies prevent XSS or in other words, have you taken this into account?

Another question: Is there a limit to how many request someone can create? Otherwise malicious users could make your service a "Spam Bot" by creating dummy help requests and all registered people will receive emails.

**Comment by kenodressel** [comment]
We tried some XSS and react automatically escapes any text it posts. So XSS seems to be a non-issue for now.

There is currently no fixed limit, we can manually ban accounts. I agree this should be done but we need a more holistic concept, we are also thinking about approving requests first before they get published or automatically flag them. If you have expertise / or know anyone who has I would gladly involve you/them in this process.

**Comment by kenodressel** [comment]
detailed in #63
