### ISSUE TITLE
Change wording "\d nachrichten erhalten"

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#30]
this seems to be an issue since people think they should have received messages. We should clearly communicate that these are responses to the post.

**Comment by jagaSto** [comment]
how about changing the wording to something like:
*  "\d Helfer gefunden"
* "\d helfende Hände gefunden"
*  "\d Helden gefunden"

or something more explanatory, like:
* "Diese Anzeige hat bereits \d Helfer gefunden"

**Comment by Maurice22** [comment]
I went with "\d Antworten erhalten" as receiving an answer not necessarily indicate that the person received the required help.

Opinions?

**Comment by kenodressel** [comment]
I agree, lets go with this for now and see if anything changes.
