### ISSUE TITLE
Development StarterKit

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#33]

**Comment by Maurice22** [comment]
Do you have more information regarding this?

**Comment by kenodressel** [comment]
The idea would be to add a small general disclaimer about the purpose of this repo. Add an url to our page and then make a seperate section below with technical details.

**Comment by Maurice22** [comment]
This should be extended. The readme should include all relevant information to get the platform running on a new environment. (i.e. firebase config, GitHub pages, etc.)

**Comment by tgraupne** [comment]
Implemented with the lasted README update
