### ISSUE TITLE
Coordinate Help for the Project, outsourceing tasks

### ISSUE THREAD

**Issue by DaAngus** [kenodressel/quarantine-hero#47]
I am very thankful for the Project and would like to contribute.
Besides the core project, are there any ways to do so?
- Raising awareness is one point here:
https://github.com/kenodressel/quarantine-hero/projects/1  
- Answering Support questions, or filtering them
- Report malicious requests or spam, filter reports
- Translations or localization for the content
- Maybe helping people to translate help requests to the local language

**Comment by scottym5797** [comment]
+1 also interested in contributing

**Comment by kenodressel** [comment]
Nice we are working on cleaning up the repo today, adding labels and publishing the currently private part of our code. This should be ready by tomorrow before noon.

**Comment by tgraupne** [comment]
Hey there, during the last couple of days, we worked on a comprehensive Getting Started Guide which should help us bringing contributors up-to-speed.

We also started a collaboration between us and other corona-help-organisations here:
https://github.com/CoronaSupportNetwork

As Keno mentioned, we further introduced labels and @florianschmidt1994 and I are trying to coordinate open source contributions.

If you'd like to contribute, we could have a chat about that :-D

**Comment by tgraupne** [comment]
Hi @DaAngus, hi @scottym5797, we updated our documentation again by adding a dedicated markdown file elaborating on our contribution approach. If you still like to help us out and support our cause, I'd like to invite you to reading it get in touch with me.
Best wishes and take care, Tom
