### ISSUE TITLE
Dashboard error "Missing or insufficient permissions"

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#48]
Dashboard throws error "Missing or insufficient permissions" and notification registrations not deletable.

**Comment by kenodressel** [comment]
This seems like an even bigger problem in firefox because there the `&times` icon is not even clickable

**Comment by Maurice22** [comment]
Same in Chrome

**Comment by timjb** [comment]
This might be caused by the dashboard code using '0' as a fallback for loading requests for help and notifications. If that is the cause, then this issue will be fixed by my PR https://github.com/kenodressel/quarantine-hero/pull/78.

**Comment by Maurice22** [comment]
@kenodressel ?

**Comment by kenodressel** [comment]
Well should be fixed then, can anyone confirm?

**Comment by Maurice22** [comment]
Confirming no "Insufficient permission" error anymore
