### ISSUE TITLE
List responses on dashboard

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#52]
To be discussed but we get requests from people who are unable to receive their responses.

**Comment by timjb** [comment]
I would like to work on this. To test whether my code is working, I would need to create some fake request for help. Should I create one in the production firestore instance or is there a way to use a separate firestore instance for development?

**Comment by kenodressel** [comment]
We are currently working on a public staging environment that can be used for these purposes. I suggest we wait until this is ready. This also enables you to actually perform the work since right now the responses can not be read.
