### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#59]
To be documented

**Comment by felixmagnus** [comment]
Hey, I'd like to help working on implementing a map overview of the help requests :-) 

I already got the project cloned and running locally.

Any starters on what you had in mind for the map view?

I thought of some toggle to switch between list and map view.

The list view stays the same and the map could show all requests based on their PLZ.

Any input would be appreciated :-)

**Comment by kenodressel** [comment]
Hey @felixmagnus,
great! We were brainstorming about it but nothing really to detailed. We thought maybe we could use polylines to outline the postal code regions. We also thought to additionally offer it as a standalone page so it could be implemented by external sites. Other than this we would be super happy if you could roughly follow our design & colors. If you need specific input feel free to write here and we can contact our designers.

**Comment by felixmagnus** [comment]
Cool :-) I'll follow the general design of the page, no problem.

I'll see what I can do - will probably start integrating it somewhere around the FilteredList (as I got the data available there and don't have to worry about passing it around) and will have a look at extracting it (so it can be used in a standalone page) afterwards.

**Comment by felixmagnus** [comment]
Hey @kenodressel 

So @friep and I started working on it, and we have come as far as can be seen on this branch:

https://github.com/felixmagnus/quarantine-hero/tree/feature/%2359-map

Basically we implemented a toggle and a basic display of germany as a map:

![Screenshot 2020-03-20 at 11 32 43](https://user-images.githubusercontent.com/49987425/77155899-8e1f1480-6a9e-11ea-851d-70fe6d345b52.png)


However, we just saw the following issue: https://github.com/kenodressel/quarantine-hero/issues/56

Especially the first point 

>  Migrate Database (plz --> geolocations)

seems very relevant to the functionality of the map.

As far as we undestood it, the firebase database currently has no information about the lat/lng coordinates of the help-requests, only the postal codes are available.

We could geolocate the postal-codes on-demand (for the initially 20 loaded help-requests) when rendering the map, but that would result in a lot of unneccessary traffic...

Also, only visualizing the initially 20 loaded help-requests on the map would provide no additional value, I think.

Our suggestion would be, to migrate the current database to include the lat/lng coordinates for every help-request. 

For all help-requests that are created after the migration, the frontend could geolocate the lat/lng coordinates on demand, and send them to the database to be stored.

After that, we were thinking of some kind of visualization like that:

![Screenshot 2020-03-20 at 11 31 25](https://user-images.githubusercontent.com/49987425/77155798-63cd5700-6a9e-11ea-9f46-77a0f40f01a1.png)

**Comment by kenodressel** [comment]
Hey @felixmagnus,
yes we are working on the migration and will enforce lat/lng coords for all entries. So you can assume that the entries are valid. In terms of visualization I would love something like this https://experience.arcgis.com/experience/478220a4c454480e823b17327b2bf1d4 with poly lines around the districts but I the above implementation seems fine for now. 
But be warned that it might take us 1-2 day to migrate the data source, so I think its best if you work with local test data. A sample entry would be :
```
{
"d":  {
coordinates: [0° N, 0° E]
location: "80000, Munich, Germany"
plz: "85579"
request "Help pls"
timestamp: 1584689783814
uid: "UUID"
}
g: "7zzzzzzzzz"
l: [0° N, 0° E] 
}
```
where `l` and `d.coordinates` are of type `Geopoint` from firebase.

**Comment by kenodressel** [comment]
@felixmagnus You might also be able to find a mapping of plz --> polylines / region than it should be possible without the coordinates :)

**Comment by felixmagnus** [comment]
Good idea with the local test data, did that :-) 

> @felixmagnus You might also be able to find a mapping of plz --> polylines / region than it should be possible without the coordinates :)

Unfortunately, I was not able to find any mapping of PLZ -> Polylines, the lowest resolution for borders / polylines I found was one level below bundesland...

I kept going with the cluster visualization approach, and in the current state (based on the local test data) It looks like this:

![Screenshot 2020-03-20 at 16 52 02](https://user-images.githubusercontent.com/49987425/77181109-2632f300-6acb-11ea-99b1-8b935df050bb.png)

What is still missing is proper styling for the bubbles, and a view below the map that shows the listings of the selected bubble.

Feel free to check it out on https://github.com/felixmagnus/quarantine-hero/tree/feature/%2359-map :-)

Any feedback / input is wecome.

**Comment by kenodressel** [comment]
@felixmagnus looks good already! I talked to our designer and he suggested this 
![image](https://user-images.githubusercontent.com/765921/77181596-dd2f6e80-6acb-11ea-86ca-66b5572c08a2.png)

**Comment by felixmagnus** [comment]
I like the design :-) 
I worked on it some more, and the current state is as can be seen in this video:

https://streamable.com/z3gax

This is the way it currently works with local test data.
The two things that are missing right now are the integration of real data (through an endpoint that returns **all** help-requests when opening the map-view) and the integration of a google maps api key. The map works without it, however for customization (e.g. language of the map - currently its defaulting to english) an apikey is needed (see docs of [google-map-react](https://github.com/google-map-react/google-map-react/blob/master/API.md).

**Comment by kenodressel** [comment]
This is absolutely awesome! My gosh! I love open source :)

We are working on re-integrating google maps in our setup. Feel free to also checkout our branch https://github.com/kenodressel/quarantine-hero/tree/migration/geomigration.

Until you can use the real data because some of the really old posts have some coordinates with them. This might help for testing.

**Comment by jgefele** [comment]
> Unfortunately, I was not able to find any mapping of PLZ -> Polylines, the lowest resolution for borders / polylines I found was one level below bundesland...

Have a look here: https://public.opendatasoft.com/explore/dataset/postleitzahlen-deutschland/table/

It's extracted from Open Street Map and cleaned a little bit. It's available as GeoJSON. For each PLZ you get a polygon, a point (center of gravity?) and a place name. 

Two drawbacks.
1. You would need to clean it further: there are duplications because some postcode regions consist of multiple unconnected parts and seemingly they chose to split those into multiple entries with one polygon each.
2. It's huge! You would need load postcode regions on demand and reduce their detail on lower zoom levels.

**Comment by Maurice22** [comment]
@felixmagnus We finished the database migration on the production instance so you should be able to use this to test against. Thank you so much for your efforts, it looks pretty nice ❤️ 🚀

**Comment by felixmagnus** [comment]
Very cool!!

I adapted my code a bit and now it works with the data provided by the prod instance :rocket:

I had to change the layout of the button a bit to fit with the new "radius-select" button.

It currently looks like that:

**List View:**

![image](https://user-images.githubusercontent.com/49987425/77750413-0435f500-7024-11ea-834d-a8c3e1849dc3.png)

**Map View:**
![image](https://user-images.githubusercontent.com/49987425/77750396-fda77d80-7023-11ea-9f31-087aa143534e.png)

Hope that is ok?

**Comment by florianschmidt1994** [comment]
That's pretty cool! About the mobile layout? Will we be able to scroll over the map screen to see the selected entry? I notice this problem sometimes with full-width maps where you can only scroll the map content and are unable to further scroll down on the page

**Comment by felixmagnus** [comment]
> Will we be able to scroll over the map screen to see the selected entry?

Yep, that should work. The default behavior of the map when scrolling with a single finger is is to scroll the page, not the map. It also shows a hint "Use two fingers to move the map". 

![image](https://user-images.githubusercontent.com/49987425/77756175-fafe5580-702e-11ea-8b10-13a2935a3b81.png)

**Comment by Maurice22** [comment]
Wa actually had a mock from our designer laying around where the map button was realized in the following way:

![Bildschirmfoto 2020-03-27 um 13 47 04](https://user-images.githubusercontent.com/20804369/77757412-7eb94180-7031-11ea-9f27-b7e4279cd185.png)

Would you be able to implement it like this maybe?

**Comment by felixmagnus** [comment]
I could try - implementing the button like that shouldn't be a problem.

However, in the current implementation, the "Deine Postleitzahl" Input and the "Radius-Select" Button disappear as soon as the Map View is entered, as they don't do anything in this view.

I could disable the inputs instead, but I think that would be a bit confusing.

Building the inputs to actually interact with the map (Zooming in on the entered location or showing an actual radius circle around the location) is certainly possible, but not without some additional effort.

**Comment by Maurice22** [comment]
Good point! I agree with your v1 approach :)
