### ISSUE TITLE
Internationalized Static Info Page

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#60]
Description to be added

**Comment by kenodressel** [comment]
The general idea is to introduce a new view that contains static information about the crisis, the virus, our page and places. This needs research about what content should be on the page and if there are any official link / tips that we should mention. Also translations are required.

**Comment by Maurice22** [comment]
Isn't this somewhat similar to the security page?

**Comment by kenodressel** [comment]
Yes I agree. We should basically internationalize this page just as we did with the one pagers.

**Comment by Maurice22** [comment]
We will close this specific issue and will tackle this issue once we internationalize the whole platform.
