### ISSUE TITLE
Add rate limiting to posts

### ISSUE THREAD

**Issue by kenodressel** [kenodressel/quarantine-hero#63]
Idea:
- A user can only have \d (2 for now) active posts at a time & coolDown + \d minutes
Proposed implementation:
- Frontend side check
- Firebase function onAskForHelpCreate
Things to note:
- Possibly needs additional exceptions for specific accounts but out of scope for now

**Comment by Maurice22** [comment]
We will close this and go with a captcha approach to prevent spam on the platform
