### ISSUE TITLE
Use react context api and/or hooks for user state

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#64]
There are a few ways in which the current user logged in state could be improved in our codebase.  Searching `react firebase hooks` or `react firebase context` will lead in the right direction and might help use discover some best practices in this regard.

I believe this might allow us to clean up the code base and hopefully have less of the flickering in the UI where some things are re-rendered because we check the user auth state in each view

**Comment by timjb** [comment]
I'm working on this.
