### ISSUE TITLE
Add login button 

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#76]
Add a login button in the header (i.e. next to press) and in the sidebar on mobile.

The login button should redirect users to `/signup/:returnurl` where `:returnurl` would for example be "notify-me" or "faq", i.e. whatever follows after `https://quarantaenehelden.org/#/`.

**Comment by kenodressel** [comment]
Luckily the redirect is already an existing feature and uses `/signup/:url` as path. So using `/signup/faq` would redirect a user to `/#/faq` after the signup/login is completed.

**Comment by Caopi** [comment]
looking at it

**Comment by Caopi** [comment]
implemented as requested via `signup/dashboard ` url. have to say it's a bit weird that the Logout button is in a different location (not header, but main menu) than the login button for desktop (header). Also a bit weird that it's "Logout" on Desktop and "Abmelden" on mobile.

I would suggest to normalize both to "Logout" or "Abmelden" and to move the desktop logout to the header where Login is now. What do you think?

**Comment by florianschmidt1994** [comment]
+1 for unifying the naming and calling them both 'Abmelden'. With regards to the location I would say let's go with what we have for now and we'll start a new design discussion about this with our designer later

**Comment by Maurice22** [comment]
Closed in #88
