### ISSUE TITLE
Add a press page

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#8]
We want to have a dedicated page where we can list notable press and social media mentions.
This task means that we need to

- [x] come up with a design for this page
- [x] compile an initial set of mentions from our marketing team
- [ ] come up with a design on how to link this (navbar?, landing page?)
- [ ] Implement in code

**Comment by kenodressel** [comment]
![image](https://user-images.githubusercontent.com/765921/76855075-a13ca500-6850-11ea-8746-15d9589439c0.png)
