### ISSUE TITLE
Onboarding dialog

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#86]
We would love to have an onboarding dialog where people will be displayed a dialog when they **first** enter the page (independent from the entry url). This dialog should show the "important notifications" from the current front page.

The idea is that every new user sees our notifications for what to beware of when using the platform.

The dialog should be closable by clicking a button named "Verstanden".

**Comment by Maurice22** [comment]
Reference:

![Onboarding](https://user-images.githubusercontent.com/20804369/77224188-63e35a80-6b63-11ea-8ee6-9274c4aaa3b2.png)
![Desktop HD Onboarding](https://user-images.githubusercontent.com/20804369/77224189-65ad1e00-6b63-11ea-871e-1a9844433227.png)

**Comment by funtonia** [comment]
What exactly is meant by "independent from the entry url"? As I understand it, this should be shown as an overlay on any subpage of QH (NotifyMe/SignUp/...) depending on which one the user sees first when accessing QH. Is that correct?

**Comment by Maurice22** [comment]
This is correct, whenever a user enters QH **for the first time**, the dialog should be shown.

I would suggest storing this information somewhat like the cookie consent to never show the overlay again in the same session.

**Comment by marko-ignjatovic** [comment]
Hi @funtonia, you are working on this one?

**Comment by Maurice22** [comment]
Duplicate of #119
