### ISSUE TITLE
Timestamp sorting not working while searching

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#89]
Filtered list should be sorted client-site if search is active.

Background: We can only sort by timestamp if we don't search in firebase. Hence, if the search flag is set, we need to do sorting locally.

**Comment by jagaSto** [comment]
example:

![Screenshot 2020-03-21 at 15 41 07](https://user-images.githubusercontent.com/20641332/77228845-64431c00-6b8a-11ea-96cb-faa2336331a3.png)

will check it out :)
