### ISSUE TITLE
Phone Hotline – Umbrella-Issue

### ISSUE THREAD

**Issue by florianschmidt1994** [kenodressel/quarantine-hero#95]
**Phone Hotline**
This is an umbrella issue to discuss technical and organizational aspects of how to implement a phone hotline. Please **do not start implementing** this feature until we've reached consensus about if and how we want to approach this topic.

With this being said, there are a few ideas and questions that we've discussed so far: 
- Human vs. automated hotline (pros & cons)?
- If automated → Twilio?
- How do we keep privacy on the way back if someone wants to call back? Maybe: https://www.twilio.com/docs/proxy/quickstart#purchase-a-twilio-phone-number
- What will this cost?
- Can we do something link phone deeplinks to directly connect via a proxy to the right caller?

I'm happy to get all our peoples input on this!

**Comment by BRGitH** [comment]
Hey Florian,

beim #WirVSVirusHack sind wir genau an der Sache dran und wollen die Lücke zwischen den genialen Portalen mit zahlreichen digital vernetzten Helfern und der Generation ohne Internetanschluss zu schließen.

Dafür wollen wir eine zentrale Nummer einrichten, die möglichst 24/7 erreichbar ist.
Den Anruf leiten wir an einen verfügbaren Helfer weiter - möglichst in Ortsnähe des Hilfesuchenden.
Dieser trägt dann das Hilfegesuch in bestehende online Portale oder leitet es direkt an örtliche Organisationen weiter.
Die Eintragung auf den Hilfsportalen wollen wir so weit wie möglich automatisieren.
Das wird bei der großen Anzahl und Verschiedenartigkeit auf jeden Fall eine Herausforderung, deshalb wenden wir uns zunächst an die größten.
Habt ihr eine REST Api, über die man Anfragen bei euch einstellen kann?

Unsere Lösung soll v.a. als eine Art Interface fungieren:
Wir stellen selbst keine physische Hilfe bereit, sorgen aber dafür, dass sich Hilfesuchende und Helfer besser finden.

Besteht eurerseits Interesse sich da zu connecten?

**Comment by wederer** [comment]
I have previously built a Hotline prototype with Twilio and can provide you with an example if needed.

**Comment by tgraupne** [comment]
Hi @florianschmidt1994, what would you thin about closing this issue for now? Especially since we decided to postpone it again.

**Comment by florianschmidt1994** [comment]
Agree! Thanks everybody for weighing in on this issue, but we've decided to not pursue this for now. If we ever want to offer a hotline, we want it to be staffed with actual humans and for now we consider this to be out of scope and out of our capacity.
