### ISSUE TITLE
Wording, Grammar and Spelling Check

### ISSUE THREAD

**Issue by Maurice22** [kenodressel/quarantine-hero#99]
We should make sure our wording is consistent (i.e. Höflichkeitsanrede, Personalpronomen i.e. Du vs. Sie, etc.)

Furthermore we need to check the grammar and spelling.

@kenodressel Any idea how to hand this out to people outside github :D

**Comment by kenodressel** [comment]
Not sure tbh but I guess we can just listen to feedback and keep this issue open for now.

**Comment by Maurice22** [comment]
I received the first feedback:

HOME
- Ansprachen wie Euch, Deine etc. groß schreiben (gilt für gesamte Webseite)
- konsistente Ansprache: entweder ihr oder du, wechselt auf der Website (Würde Du präferieren weil ist persönlicher) 
- Startseite: eure Mitmenschen in eurer Nachbarschaft, Dopplung "eure"

FAQ
- Quarantäneort -> ein Wort, Bindestrich vermeiden, ist aber eventuell Geschmackssache
- wie funktioniert Quarantänehelden: "wir leiten deine Nachricht an den/die Anfragensteller*in weiter, die dann zu dir Kontakt aufnehmen" -> aufnimmt im singular, weil hier durch das gendern die weibliche Form gemeint ist und nicht der Plural
- wieso sollte ich das tun -> Quarantänesituation würde ich hier eventuell auch zusammenschreiben, einfach um Einheitlichkeit mit der Schreibweise von "Quarantänehelden" zu gewährleisten, das ist ja auch nicht mit Bindestrich, s.o. eventuell Geschmackssache
- wie stelle ich sicher, dass ich Geld bekomme: generell Konsistenz in Schreibweise von "QuarantäneHelden", soll das H generell groß? wenn ja dann auch hier in der Antwort
- wieso sollte ich das tun -> des Virus und nicht des Virus'
- wie weiß ich, dass die Person wirklich in quarantäne ist -> woher anstelle von wie in der Fragestellung
- wie werden Daten verwendet -> satzbau "öffentlich an alle Nutzer gezeigt" ist falsch. Außerdem gendern -> "allen Nutzer*innen gezeigt"
- in der selben Antwort -> anfragensteller*in

**Comment by DaAngus** [comment]
To get help from outside github I would suggest discord, not because I like it but because 
its simple, well known and not behind a huge registration wall (unregistered accounts can participate)
Its easy to share a Invite link.
It has been proven by other opensource projects to be useful for communication and development.

**Comment by funtonia** [comment]
CTA-Button should be "Benachrichtige mich, wenn jemand in meiner Nähe Hilfe braucht!" (Comma missing).

**Comment by florianschmidt1994** [comment]
@DaAngus while I do like Discord myself, I would prefer not to open a discord chat for now. We are currently pretty busy monitoring the existing channels and another one would only add to the existing workload

**Comment by tgraupne** [comment]
I created an issue about updating our FAQs #182
